import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { CreatePostButton } from '@/components/ui/create-post-button'
import { LeftSidebar } from '@/components/left-sidebar'
import RightSidebar from '@/components/right-sidebar'
import Bottombar from '@/components/ui/bottom-bar'
import { Topbar } from '@/components/top-bar'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black flex flex-col h-screen overflow-hidden`}
      >
        <Topbar />
        <main className="flex flex-row max-w-7xl w-full mx-auto flex-grow overflow-hidden mt-20">
          <LeftSidebar />

          <section className="main-container relative flex-grow overflow-auto">
            <div className="absolute bottom-24 right-4">
              <CreatePostButton
                displayMd="hidden"
                position="fixed bottom-24 right-4"
              />
            </div>
            <div className="w-full max-w-4xl h-full py-4">{children}</div>
          </section>

          <RightSidebar />
        </main>
        <Bottombar />
      </body>
    </html>
  )
}
